# Generated by Django 5.0.3 on 2024-05-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_odev', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kisi',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='KisiMail',
            new_name='UserMail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='KisiPassword',
            new_name='UserPassword',
        ),
    ]
