# Generated by Django 5.0.3 on 2024-05-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_odev', '0002_rename_kisi_user_rename_kisimail_user_usermail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Kisi',
        ),
        migrations.RenameField(
            model_name='kisi',
            old_name='UserMail',
            new_name='KisiMail',
        ),
        migrations.RenameField(
            model_name='kisi',
            old_name='UserPassword',
            new_name='KisiPassword',
        ),
    ]
